### ISSUE TITLE
Give users the option to enter own API credentials in Escape Pod

### ISSUE THREAD

**Issue by xanathon** [bussardrobbie/DDL-KB-Kanban#28]
Despite the fact that a (quote) "fully functioning" Vector was promised with Kickstarter in the Escape Pod campaign so far only parts are actually working.

Knowledge graph and weather are missing. Knowledge graph is a central part of Vectors functionality.

On Discord RLB said that "DDL cannot reveal DDL's API access credentials of the external APIs Vector users". That may be so.

However: add options in the Escape Pod that allow users to use the APIs themselves. I do not know what weather provider you use but it should be as easy as adding an API url, a user token and an access token on a settings page after a user registered for the API with some additional parameters done by DDL in Escape Pod so the Vectors tethered to that Escape Pod then use the direct API connection.

I guess knowledge base may be more difficult depending on what solution is used here, but basically the same should apply.

**Comment by bussardrobbie** [comment]
I have already opened an issue in the DDL internal GitHub repo for Escape Pod as a feature request. This issue does not belong in this repository as it's not the repository's dedicated use case. Issue closed.

**Comment by cyb3rdog** [comment]
To be completely fair with each other, it is very nice to have this resulted into this issue beeing moved acrross to its proper repository and therefore to be considered and adressed by the dedicated people. However, that internal repositories of yours are not available to the public, so the public dont have any other place to raise such issues, or ideas, than this repo of yours (except for the support email, which is yet again not exactly best place for shared community contributions). Therefore, i would like to pin this [Issue](https://github.com/bussardrobbie/DDL-KB-Kanban/issues/29) as a resolution proposal for scenarios like this.

**Comment by bussardrobbie** [comment]
@cyb3rdog That Issue is noted and I've looked through it. I'm open to an ideas portal where people can submit ideas and vote on them to drive our roadmap. However, I haven't found a platform yet that I enjoy for such a thing, and that would tie in to our existing systems easily. I'm still looking into this.

**Comment by xanathon** [comment]
Exactly what cyb3erdog comments. Either you want comments and suggestions or you do not want them. But do not try to create an illusion of taking suggestions to just close them with "is done elsewhere" without giving a distinct place to go. But this is part of the fragmentation problem I have described elsewhere.

**Comment by cyb3rdog** [comment]
Now @xanathon, now is your time to shine. This is the right place and time for you to come up with a solution, a software with low to no costs, which could be easily integrated into existing, and perhaps under-the-construction infrastructures, again, at low to no costs. You said that you've done this once and sugessted something like that already, right? Dont forget that time for interfacing, integration, administration and than the daily maintance of such products are calculated as costs, and that all products or subsystems included into corporate enterprises should have a calculable ROI.
@bussardrobbie I greatly appretiate your open minded approach, and completely undestand that developong and implementing internal company processes and systems is serious topic. Thanks for the answer!
