### ISSUE TITLE
Dedicated CCIS Article(s)

### ISSUE THREAD

**Issue by bussardrobbie** [bussardrobbie/DDL-KB-Kanban#5]
Users need to know how to enter CCIS, and what each screen/value means. Giving people the power to troubleshoot issues with their Vectors using CCIS would be invaluable!

**Comment by bussardrobbie** [comment]
This is completed and now live here:
https://support.digitaldreamlabs.com/article/531-vector-ccis

I'm debating whether to keep this as one article or split it out into a total of 9 articles: 1 which details how to enter CCIS and manipulate the robot in CCIS, and 8 more- one for each CCIS screen with details as to what's on it and its implications. Keeping it as one article is good for continuity, but may be complex and less approachable for some users, where a broken-out category of articles may leave some users searching for the right place to find information about whatever sensor they actually need to look for, etc. 

Feedback and suggestions welcomed.

**Comment by moribundant** [comment]
Yes, "...with details as to what's on it and its implications." Specifically, **what to do** for each of the NETWORK indicators:

NETWORK: Displays the results of a pass/fail check for network conditions. Possible codes are:
AVAILABLE
CONNECTIVITY
TLS
AUTH
BANDWIDTH
CHECKING...

For example, I often see 'CONNECTIVITY' and IIRC it is in red. So what should I do to remove this and get 'AVAILABLE', which IIRC is in green?

**Comment by bussardrobbie** [comment]
@moribundant Yeah, this definitely could use enumeration and it's on the agenda- but effectively I have to chase down and trace back the code that generates those and then understand the conditions they might appear in. Some are helpful, but effectively "CONNECTIVITY" usually means Vector couldn't ping the DDL server through your gateway during the last ping test. Could be firewall related, but start with rebooting your router.

If Vector displays "TLS" or "AUTH" then there's no choice but to do a Clear User Data reset, as those are authentication errors and hard to get past if the credentials stored on the robot are too old to update (usually what happens when you see "TLS") or there's a mismatch of server credentials to robot credentials ("AUTH" error).

I'll add at least those 2 into the article when I get some time, and then the rest I'll need to trace back in the code and verify the conditions of what might cause them.

Thanks for the feedback!
