### ISSUE TITLE
Obtaining Logs

### ISSUE THREAD

**Issue by bussardrobbie** [bussardrobbie/DDL-KB-Kanban#60]
Need documentation to obtain robot logs via vector-setup.ddl.io.

Text will be the main format but narrated video should be included if possible, since this process can be a bit more technical and we can catch a few small edge cases.

**Comment by moribundant** [comment]
Please, no video. A clean write-up would be nice.

**Comment by bussardrobbie** [comment]
@moribundant The article would contain both. I am always in favor of multiple content types for instructional content. For an example of what I mean, see: https://support.digitaldreamlabs.com/article/358-launching-your-escape-pod-2

The above article contains both a detailed, narrated video as well as detailed instructions. The initial issue was a VERY quick submission to jog my memory when I get the time to write it. I'll edit to flesh that out.

**Comment by moribundant** [comment]
OK, that's different. I envisioned a YouTube yawner.

**Comment by bussardrobbie** [comment]
Revision one of this article is complete. This does not yet include a video, but eventually I will expand it to include a video of the process and some tips or tricks on unpacking and examining the logs for folks who are a little more experienced on the tech side.

https://support.digitaldreamlabs.com/article/523-collecting-logs-vector

**Comment by moribundant** [comment]
Might want to add a short note on how to do this with OSKR (logcat).

**Comment by bussardrobbie** [comment]
Not a bad idea. I may or may not put that in a separate OSKR-centric article but I will think on this. Thanks for the idea and feedback.

**Comment by moribundant** [comment]
I know how to do it, both with ssh and (now, thanks Wire!) with adb. Just thinking about the community. What I have noticed is that there are significant differences between Prod owners, OSKR owners and then Prod+EP and OSKR+EP owners. Colossal confusion and don't get me started on the 'Victor' owners. We just need some organization. Not to drag this out, but also between Mac and Windoze. The latter just complicates things, Anki used Macs.
