### ISSUE TITLE
Change Hosting for OSKR Documentation

### ISSUE THREAD

**Issue by bussardrobbie** [bussardrobbie/DDL-KB-Kanban#66]
The current OSKR documentation is very unwieldy to change; Markdown must be modified, the changes must be built, then another team member must be notified to deploy the changes to staging for review before publishing.

Changing the host to our support desk vendor's hosting will significantly streamline this process and allow for smaller changes more frequently without tying up resources.

**Comment by bussardrobbie** [comment]
Took a bit, but OSKR documentation is now swapped over (same URL; oskr.ddl.io)- the CSS has also been changed for responsiveness on mobile and tablet configurations.

Now to clarify documentation, separate it into individual articles where needed, and move from there.

**Comment by moribundant** [comment]
Nice! Love the layout, but you should have made [oskr.ddl.io](http://oskr.ddl.io) clickable in your msg 😉
